### PR TITLE
Hit API implementation

### PR DESCRIPTION
**Pull request by Caren-Koroeny**
- use https://www.notion.so/microverse/Leaderboard-API-service-24c0c3c116974ac49488d4eb0267ade3 API.

- Created a new game by using the API.

-  saved the ID of the game that was returned by API.

- Implemented the "Refresh" button that gets all scores for a game created from the API (receiving data from the API and parsing the JSON).

- Before clicking the Refresh Button

Screenshot from 2023-02-08 17-20-33

After Refresh is clicked:
Screenshot from 2023-02-08 17-19-39
 
- Implemented the form "Submit" button that saves a score for a game created (sending data to the API).

- Used `arrow functions` instead of the `function` keyword.
-  Used `async` and `await` JavaScript features to consume the API 
       
 Screenshot from 2023-02-08 17-17-34

### CODE REVIEW

**Review by frank1738 — COMMENTED** [review]
Hi @Caren-Koroeny , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Your readme is missing an important header, `key features`,.  Kindly include it and resubmit your project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Caren-Koroeny** [comment]
- Hello Frank, kindly why is it invalid?

- I  added the key Feature.

Screenshot from 2023-02-08 17-39-18

**Review by AmaduKamara — COMMENTED** [review]
# Status: Invalid SUbmission ❌ ❌ ❌

Hi @Caren-Koroeny,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is missing some important headers in your README.

- [ ] Kindly add the Key Features in your Table of contents below Tech Stack and also list the Key Features your app has below the client, server, and database just as it's in the [README Template](https://github.com/microverseinc/readme-template). In this case, the features you measured at the bottom of your README, I'm sure supposed to be at the top and that one at the bottom is meant for Future Features you would like to add to your app. Kindly make those changes and resubmit again 👍🏽

Screenshot 2023-02-08 at 2 49 30 PM

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Review by mukhammadrizooff — APPROVED** [review]
Hi @Caren-Koroeny, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
